#!/usr/bin/env python3
"""Generate the check-status table in README.md from the checks themselves.

A hand-maintained status table is the same failure mode this repo exists to
catch: it reads as current long after it stopped being true. So the table is
generated, written between markers in README.md, and CI verifies it is up to
date the same way it verifies the bibliography is normalized.

    python3 tools/status_table.py            # rewrite the table in README.md
    python3 tools/status_table.py --check    # exit 1 if the table is stale
    python3 tools/status_table.py --stdout   # print it, touch nothing

Counts come from the tools directly (`--json` where available, the cached CSVs
otherwise), never from a copy kept somewhere else.
"""
from __future__ import annotations

import argparse
import csv
import json
import re
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
README = REPO_ROOT / "README.md"
BEGIN = "<!-- BEGIN CHECK STATUS (generated by tools/status_table.py) -->"
END = "<!-- END CHECK STATUS -->"

PASS, FAIL, INFO = "✅", "❌", "ℹ️"


def run(cmd: list[str]) -> tuple[int, str]:
    proc = subprocess.run(cmd, capture_output=True, text=True, cwd=str(REPO_ROOT))
    return proc.returncode, proc.stdout


def counts_from(detail: str, meta: dict | None) -> str:
    """Pull an `n/d` out of a check's own reported detail.

    Checks put their counts at the front of `detail` as `(n/d ...)`, which is
    also what a human reads in the terminal, so the table cannot disagree with
    the terminal output.
    """
    m = re.search(r"\((\d+)\s*/\s*(\d+)", detail or "")
    if m:
        return f"{m.group(1)} / {m.group(2)}"
    if meta:
        for a, b in (("verified", "checked"), ("passed", "total")):
            if a in meta and b in meta:
                return f"{meta[a]} / {meta[b]}"
    return "—"


def rows_from_bib() -> list[tuple]:
    code, out = run([sys.executable, "tools/stylized-facts.bib.tests.py", "--check", "--json"])
    try:
        results = json.loads(out)["results"]
    except (ValueError, KeyError):
        return [("Bibliography", "bibliography tests", FAIL, "—", "could not run")]
    rows = []
    for r in results:
        # Skip checks whose presence depends on what is installed rather than
        # on the repo. bibclean runs here but is skipped on Ubuntu, so
        # including it makes the table differ between a laptop and CI and the
        # freshness check fails on a table nobody edited.
        if r["name"] == "bibclean lint":
            continue
        advisory = r.get("advisory")
        symbol = PASS if r["ok"] else (INFO if advisory else FAIL)
        note = "coverage, advisory" if advisory else ""
        rows.append(("Bibliography", r["name"], symbol, counts_from(r.get("detail", ""), None), note))
    return rows


def rows_from_documents() -> list[tuple]:
    code, out = run([sys.executable, "tools/qmd_validate.py", "--all", "--json"])
    try:
        docs = json.loads(out)["docs"]
    except (ValueError, KeyError):
        return [("Document", "document checks", FAIL, "—", "could not run")]
    rows = []
    for doc in docs:
        for item in doc["items"]:
            # The shared bibliography check is already broken out above.
            if item["name"] == "Bibliography tests":
                continue
            symbol = PASS if item["ok"] else FAIL
            note = ""
            meta = item.get("meta") or {}
            if item["name"].startswith("Quotes"):
                extra = []
                if meta.get("partial"):
                    extra.append(f"{len(meta['partial'])} partial")
                if meta.get("keys_not_archived"):
                    extra.append(f"{len(meta['keys_not_archived'])} sources not archived")
                note = ", ".join(extra)
            if item["name"].startswith("Numeric claims") and meta.get("skipped"):
                note = f"{len(meta['skipped'])} source not archived, skipped"
            if item["name"].startswith("Local archive"):
                symbol, note = INFO, "informational"
            rows.append(("Document", item["name"], symbol, counts_from(item.get("detail", ""), meta), note))
    return rows


def rows_from_arxiv() -> list[tuple]:
    cache = REPO_ROOT / "references" / "arxiv-metadata.csv"
    if not cache.exists():
        return [("Citations", "arXiv ids match their bib entry", FAIL, "—", "no cache; run make arxiv-refresh")]
    rows = list(csv.DictReader(cache.open(encoding="utf-8")))
    bad = [r for r in rows if r["verdict"] in ("MISMATCH", "suspect")]
    missing = [r for r in rows if r["verdict"] == "not_found"]
    ok = len(rows) - len(bad) - len(missing)
    note = "; ".join(
        x for x in (
            f"{len(bad)} point at a different paper" if bad else "",
            f"{len(missing)} id not found" if missing else "",
        ) if x
    )
    return [("Citations", "arXiv ids match their bib entry", PASS if not bad else FAIL,
             f"{ok} / {len(rows)}", note)]


def rows_from_manifest() -> list[tuple]:
    manifest = REPO_ROOT / "references" / "manifest.csv"
    if not manifest.exists():
        return []
    rows = list(csv.DictReader(manifest.open(encoding="utf-8")))
    total = len(rows)
    with_pdf = sum(1 for r in rows if r["status"] == "ok")
    with_text = sum(1 for r in rows if r["status"] in ("ok", "text_only"))
    manual = sum(1 for r in rows if r["status"] == "manual_needed")
    return [
        ("Archive", "Cited works with a local PDF", INFO, f"{with_pdf} / {total}", "informational"),
        ("Archive", "Cited works with local fulltext", INFO, f"{with_text} / {total}",
         "what the quote checks read"),
        ("Archive", "Works needing manual download", INFO, f"{manual} / {total}",
         "paywalled; see references/manifest.csv"),
    ]


def build_table() -> str:
    rows = rows_from_bib() + rows_from_arxiv() + rows_from_documents() + rows_from_manifest()
    lines = [
        BEGIN,
        "",
        "| | Check | Status | Count | Notes |",
        "|---|---|:---:|---:|---|",
    ]
    last_group = None
    for group, name, symbol, count, note in rows:
        shown = f"**{group}**" if group != last_group else ""
        last_group = group
        lines.append(f"| {shown} | {name} | {symbol} | {count} | {note} |")
    lines += [
        "",
        f"{PASS} passing &nbsp; {FAIL} failing &nbsp; {INFO} informational or advisory "
        "(reported, does not block a commit)",
        "",
        END,
    ]
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="Exit 1 if README.md is out of date.")
    ap.add_argument("--stdout", action="store_true", help="Print the table, write nothing.")
    args = ap.parse_args()

    table = build_table()
    if args.stdout:
        print(table)
        return 0

    text = README.read_text(encoding="utf-8")
    if BEGIN not in text or END not in text:
        print(f"README.md has no status-table markers; add:\n{BEGIN}\n{END}")
        return 1

    updated = re.sub(
        re.escape(BEGIN) + r".*?" + re.escape(END), lambda _: table, text, flags=re.DOTALL
    )

    if args.check:
        if updated != text:
            print("README.md check-status table is stale. Refresh with: make status")
            return 1
        print("README.md status table is up to date")
        return 0

    if updated != text:
        README.write_text(updated, encoding="utf-8")
        print(f"updated {README}")
    else:
        print("README.md status table already up to date")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
